---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pgo-pgbackrest-secrets
spec:
  target:
    name: pgo-pgbackrest-secrets
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  dataFrom:
    - extract:
        key: pgbackrest/mss-keycloak-pgha/cipher
