apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: regapp-client
  labels:
    client: regapp-client
spec:
  realmSelector:
    matchLabels:
      realm: mss
  serviceAccountClientRoles:
    realm-management:
      - create-client
      - manage-identity-providers
      - view-realm
      - view-users
      - query-users
      - view-clients
      - query-groups
      - manage-clients
      - manage-events
      - impersonation
      - view-authorization
      - manage-users
      - query-realms
      - manage-realm
      - view-identity-providers
      - view-events
      - realm-admin
      - manage-authorization
      - query-clients
  client:
    attributes:
      access.token.lifespan: "60"
      backchannel.logout.revoke.offline.tokens: "false"
      backchannel.logout.session.required: "true"
      client_credentials.use_refresh_token: "false"
      display.on.consent.screen: "false"
      exclude.session.state.from.auth.response: "false"
      id.token.as.detached.signature: "false"
      oauth2.device.authorization.grant.enabled: "false"
      oidc.ciba.grant.enabled: "false"
      require.pushed.authorization.requests: "false"
      saml.artifact.binding: "false"
      saml.assertion.signature: "false"
      saml.authnstatement: "false"
      saml.client.signature: "false"
      saml.encrypt: "false"
      saml.force.post.binding: "false"
      saml.multivalued.roles: "false"
      saml.onetimeuse.condition: "false"
      saml.server.signature: "false"
      saml.server.signature.keyinfo.ext: "false"
      saml_force_name_id_format: "false"
      tls.client.certificate.bound.access.tokens: "false"
      use.refresh.tokens: "true"
    clientAuthenticatorType: client-secret
    clientId: regapp
    defaultClientScopes:
    - web-origins
    - roles
    - profile
    - email
    directAccessGrantsEnabled: true
    enabled: true
    fullScopeAllowed: true
    implicitFlowEnabled: false
    nodeReRegistrationTimeout: -1
    optionalClientScopes:
    - address
    - phone
    - offline_access
    - microprofile-jwt
    protocol: openid-connect
    protocolMappers:
    - config:
        access.token.claim: "false"
        claim.name: cilogon_idp_name
        id.token.claim: "true"
        jsonType.label: String
        user.attribute: cilogon_idp_name
        userinfo.token.claim: "true"
      name: cilogon_idp_name
      protocol: openid-connect
      protocolMapper: oidc-usermodel-attribute-mapper
    - config:
        access.token.claim: "false"
        claim.name: preferred_username
        id.token.claim: "true"
        jsonType.label: String
        user.attribute: username
        userinfo.token.claim: "true"
      name: username
      protocol: openid-connect
      protocolMapper: oidc-usermodel-property-mapper
    - config:
        access.token.claim: "true"
        claim.name: mss_research_domain
        id.token.claim: "true"
        jsonType.label: String
        user.attribute: mss_research_domain
        userinfo.token.claim: "true"
      name: mss_research_domain
      protocol: openid-connect
      protocolMapper: oidc-usermodel-attribute-mapper
    - config:
        access.token.claim: "true"
        claim.name: accepted_terms
        id.token.claim: "true"
        jsonType.label: String
        user.attribute: accepted_terms
        userinfo.token.claim: "true"
      name: accepted_terms
      protocol: openid-connect
      protocolMapper: oidc-usermodel-attribute-mapper
    - config:
        access.token.claim: "true"
        claim.name: clientHost
        id.token.claim: "true"
        jsonType.label: String
        user.session.note: clientHost
      name: Client Host
      protocol: openid-connect
      protocolMapper: oidc-usersessionmodel-note-mapper
    - config:
        access.token.claim: "true"
        claim.name: clientAddress
        id.token.claim: "true"
        jsonType.label: String
        user.session.note: clientAddress
      name: Client IP Address
      protocol: openid-connect
      protocolMapper: oidc-usersessionmodel-note-mapper
    - config:
        access.token.claim: "true"
        claim.name: clientId
        id.token.claim: "true"
        jsonType.label: String
        user.session.note: clientId
      name: Client ID
      protocol: openid-connect
      protocolMapper: oidc-usersessionmodel-note-mapper
    publicClient: false
    redirectUris:
    - https://regapp.mss.mghpcc.org/*
    serviceAccountsEnabled: true
    standardFlowEnabled: true
